name: Deploy to Azure DevOps Pipeline

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Echo Azure DevOps Token Length (For Debugging)
        run: echo "Token Length: ${#AZURE_DEVOPS_TOKEN}"
        shell: bash
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}

      - name: Trigger Azure DevOps Pipeline
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: "https://dev.azure.com/BeluvigiShreegagana/terraform-task"
          azure-pipeline-name: "terraform-task"  # Change this if your pipeline name is different
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
